### ISSUE TITLE
Questions about the BERT version of span-aste.

### ISSUE THREAD

**Issue by zlyoung** [wireless911/span-aste#1]
Thank you very much for your open source pytorch version of span-aste network code.   I replaced the encoder of LSTM version span-aste with BERT. However, the accuracy, recall and F1 score during training and verification are all 0, and I could not find the error. Do you have a plan to develop the BERT version span-aste? Or could you tell me the way to change the model to BERT encoder?

**Comment by wireless911** [comment]
I have implemented the version of bert, which is not open source yet. For the bert part, you need to consider the issue of sequence alignment,because the wordpiece tokenizer used by bert, may be helpful [here](https://blog.csdn.net/qq_33293040/article/details/110432154)

**Comment by zlyoung** [comment]
Thank you for your reply. I have implemented BERT version span-aste.
