### ISSUE TITLE
batchsize的问题

### ISSUE THREAD

**Issue by nlpxjg** [wireless911/span-aste#10]
作者您好，我在batchsize = 1和 batchsize = 4上都进行了试验，但是batchsize = 4的结果下降了10%，请问一下原因可能是什么？
期待您的回复！

**Comment by wireless911** [comment]
个人观点： batch_size 为4时，span的会根据同一batch中最长的sentence来选取len(sentence)*0.5的候选集，从而导致最终结果的差异，建议看下paper中batchsize的设置（1）
