### ISSUE TITLE
全部的代码吗？

### ISSUE THREAD

**Issue by motuomumu** [wireless911/span-aste#11]
作者您好，请问这就是论文的全部代码吗？我看到这篇论文还有另外一个代码有好多呀。

**Comment by wireless911** [comment]
是Bert版本的全部代码

**Comment by motuomumu** [comment]
ok,thank you very much.




墨脱小琳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wireless911/span-aste"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 上午8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wireless911/span-aste] 全部的代码吗？ (Issue #11)





 
是Bert版本的全部代码
