### ISSUE TITLE
请问作者为什么损失和原作者的不一样？

### ISSUE THREAD

**Issue by micrazy** [wireless911/span-aste#14]
您好，您的工作非常优秀，但我有个问题想请教下，原论文里，损失是取了ner_loss和relation_loss之和，但是您实现的时候用了loss = 0.2 * loss_ner + loss_relation，请问是出于什么考虑呢？

**Comment by wireless911** [comment]
我在测试的时候给loss加了权重，你可以尝试下不同的权重得到的结果

**Comment by micrazy** [comment]
感谢作者答复~
