### ISSUE TITLE
[BUG]性能感觉很差

### ISSUE THREAD

**Issue by micrazy** [wireless911/span-aste#17]
作者您好，您的工作对我们很有帮助，唯一的遗憾是性能这块比较差：我们用sanic做了服务接口部署，长度为40包含三个三元组的文本，在13并发下95%响应时间将近4s，TPS只有不到10，是因为算法内部有笛卡尔积的原因吗，导致复杂度为O(n^2)?

**Comment by cwqJim2023** [comment]
您好，请问你解决性能问题了吗？

**Comment by micrazy** [comment]
> 您好，请问你解决性能问题了吗？

解决不了

**Comment by wireless911** [comment]
性能的问题可能要优化代码了，代码里有笛卡尔积，时间复杂度会有点大，我使用模型主要是离线推理，可能没有碰到实时推理的问题

**Comment by cwqJim2023** [comment]
推理时效性上要优化的话，@wireless911有什么建议吗，那些地方入手比较好一些
