### ISSUE TITLE
bert模型问题

### ISSUE THREAD

**Issue by lzf00** [wireless911/span-aste#5]
![image](https://user-images.githubusercontent.com/51185068/190978457-c13b3b5b-0fa6-4d33-bee1-f0ac7b1feb5c.png)
我安装你的模型，不知道为什么会碰到这个错误，之前没遇到过的

**Comment by wireless911** [comment]
我没有遇到向你一样的问题，我觉得你可以先把环境问题排除掉，依赖包版本可以参考我requirements.txt

**Comment by lzf00** [comment]
> 

感谢回复，我已经解决了这个问题，不知道这个load_msra_ner_without_dev里面，有什么没有被定义？并且需要的四个文件都下载了
![image](https://user-images.githubusercontent.com/51185068/191216640-de1cd6eb-0374-41d3-b00a-fe0c1789f9f2.png)
