### ISSUE TITLE
模型预测结果的保存

### ISSUE THREAD

**Issue by lzf00** [wireless911/span-aste#6]
我想把训练和测试的推理结果保存下来，该怎么改？
我输出了这些指标，但不是很懂。。。。
![image](https://user-images.githubusercontent.com/51185068/191445663-237eef9c-2c06-419a-98f7-14d67d7ad4e6.png)

**Comment by wireless911** [comment]
在训练阶段，你不太需要去把这些结果输出到文件中，你可以在模型训练结束之后，在推理时保存最终的结果，包括验证集和测试集的指标和保存三元组提取的结果

**Comment by lzf00** [comment]
> 在训练阶段，你不太需要去把这些结果输出到文件中，你可以在模型训练结束之后，在推理时保存最终的结果，包括验证集和测试集的指标和保存三元组提取的结果

明白了，我用自己的数据集只训练了10个epoch，在test的时候输出预测结果，一个结果都没预测出来，是不是epoch太少的原因，还有我需要根据自己的实体长度调整span的长度吧？
![image](https://user-images.githubusercontent.com/51185068/191680596-fff13af7-8d05-497a-a3b6-583e743e3bef.png)

**Comment by wireless911** [comment]
训练模型的可以使用以下的命令
`python train.py \
  --bert_model bert-base-uncased \
  --batch_size 1 \
  --learning_rate 5e-5 \
  --weight_decay 1e-2 \
  --warmup_proportion 0.1 \
  --train_path data/15res \
  --dev_path data/15res \
  --save_dir ./checkpoint \
  --max_seq_len 512 \
  --num_epochs 10 \
  --logging_steps 30 \
  --valid_steps 50`


同时可以用tensorboard的可视化训练过程的loss 和指标变化曲线

**Comment by bale-le** [comment]
> 我想把训练和测试的推理结果保存下来，该怎么改？ 我输出了这些指标，但不是很懂。。。。 ![image](https://user-images.githubusercontent.com/51185068/191445663-237eef9c-2c06-419a-98f7-14d67d7ad4e6.png)

你好，想问下你最后是怎么保存测试结果的，三元组的保存，我不是很明白
