### ISSUE TITLE
span-level 的长度

### ISSUE THREAD

**Issue by lzf00** [wireless911/span-aste#7]
![image](https://user-images.githubusercontent.com/51185068/191639018-f2364697-54a9-44cf-b0f1-093426d73bf7.png)
wo我发现输入文件的span是这样的，请问span的最大长度为10吗，我的数据集有很多长实体，请问我该怎么修改span的最大长度？

**Comment by wireless911** [comment]
`class SpanRepresentation(nn.Module):

    def __init__(self, span_width_embedding_dim, max_window_size: int = 10):
        super(SpanRepresentation, self).__init__()
        self.max_window_size = max_window_size
        self.bucket_bins = [0, 1, 2, 3, 4, 5, 7, 8, 15, 16, 31, 32, 63, 64]
        self.span_width_embedding = nn.Embedding(len(self.bucket_bins), span_width_embedding_dim)`


这个模块里max_window_size 参数就是span 的最大长度

**Comment by lzf00** [comment]
> `class SpanRepresentation(nn.Module):
> 
> ```
> def __init__(self, span_width_embedding_dim, max_window_size: int = 10):
>     super(SpanRepresentation, self).__init__()
>     self.max_window_size = max_window_size
>     self.bucket_bins = [0, 1, 2, 3, 4, 5, 7, 8, 15, 16, 31, 32, 63, 64]
>     self.span_width_embedding = nn.Embedding(len(self.bucket_bins), span_width_embedding_dim)`
> ```
> 
> 这个模块里max_window_size 参数就是span 的最大长度

**Comment by lzf00** [comment]
感谢回复，我根据自己数据集实体的长度将span-max设为35，
self.bucket_bins = [0, 1, 2, 3, 4, 5, 7, 8, 15, 16, 31, 32, 63, 64]
    self.span_width_embedding = nn.Embedding(len(self.bucket_bins), span_width_embedding_dim)`
但是不清楚self.bucket_bins的含义，我需要更改这个参数吗？

**Comment by wireless911** [comment]
不需要，具体的原理可以去看paper里面的介绍
