### ISSUE TITLE
用提供的15res，模型预测结果全为0

### ISSUE THREAD

**Issue by zy85** [wireless911/span-aste#8]
![image](https://user-images.githubusercontent.com/44042842/193440366-96e397e8-b59f-44ae-811b-acefbdf1bcc4.png)

**Comment by wireless911** [comment]
你可以把你训练的参数贴出来

**Comment by nlpxjg** [comment]
> 
你好，我也遇到了同样的问题，训练参数就是你github主页的那个，结果全是0.
<img width="314" alt="image" src="https://user-images.githubusercontent.com/94729199/198835771-cc8cdd09-e91d-4a35-acf8-f60c2ba804a1.png">

**Comment by wireless911** [comment]
是训练过程全是0吗，我刚拉了下代码，测试没问题的啊，模型迭代到epoch=2 时的结果

Evaluation precision: 0.25000, recall: 0.00418, F1: 0.00823
best F1 performence has been updated: 0.00000 --> 0.00823

**Comment by zy85** [comment]
多训练了几次可以了 ，但是训练时前半个小时结果也一直都是0

**Comment by zy85** [comment]
![c4a9cc40ba3aea0a718514f7e8d856e](https://user-images.githubusercontent.com/44042842/199162216-efb9c6fe-845d-4b3d-9467-bc31bbb89989.jpg)
请问一下我的结果和论文结果不同是怎么回事

**Comment by zy85** [comment]
> > 
> 
> 你好，我也遇到了同样的问题，训练参数就是你github主页的那个，结果全是0. <img alt="图像" width="314" src="https://user-images.githubusercontent.com/94729199/198835771-cc8cdd09-e91d-4a35-acf8-f60c2ba804a1.png">

我是多跑了几次，然后过了两天又可以了，不知道具体原因在哪里

**Comment by wireless911** [comment]
> ![c4a9cc40ba3aea0a718514f7e8d856e](https://user-images.githubusercontent.com/44042842/199162216-efb9c6fe-845d-4b3d-9467-bc31bbb89989.jpg) 请问一下我的结果和论文结果不同是怎么回事

你的结果是在验证集上的f1值吗，以下是我在验证集上最好的结果，如果f1值一直很低，你可以尝试调整下参数试试

Evaluation precision: 0.71053, recall: 0.68936, F1: 0.69978
best F1 performence has been updated: 0.69264 --> 0.69978

**Comment by nlpxjg** [comment]
> f1

你好 模型现在的代码能够在测试集上测试吗？
期待您的回复！

**Comment by zy85** [comment]
可以在测试集上跑，我使用15res的测试集，评估精度：0.65094，召回率：0.60659，F1：0.62799

**Comment by Necro1yte** [comment]
我训练结果也全是0，你们是怎么解决的啊
